categories_text = [
["Independent Contract","Revenue"],
["Book sales","Revenue"],
["Miscellaneous","Revenue"],
["Business Expense","Business"],
["Reimbursable","Business"],
["Taxes","Business"],
["Rent","Fixed"],
["Renter's Insurance","Fixed"],
["Health Insurance","Fixed"],
["Healthcare","Fixed"],
["Electricity","Fixed"],
["Natural Gas","Fixed"],
["Internet","Fixed"],
["Cell Phone","Fixed"],
["Groceries","Fixed"],
["Transportation","Fixed"],
["Social","Discretionary"],
["Restaurants","Discretionary"],
["Shopping","Discretionary"],
["Apartment","Discretionary"],
["Travel","Discretionary"],
["Gym","Discretionary"],
["Donation","Discretionary"],
["Education","Discretionary"],
["Hobbies","Discretionary"],
["Fees","Discretionary"],
["Retirement","Retirement"],
]
